### ISSUE TITLE
Lists are not consecutive

### ISSUE THREAD

**Issue by deavmi** [deavmi/JustInfo#2]
Needs work around (it's a Markdown rendering thing): https://github.com/deavmi/JustInfo/blob/master/CONTRIBUTING.md

**Comment by Walkman100** [comment]
Oh this. I've had to work around this when making [markdown licenses](https://github.com/Walkman100/KeyStatus/commit/08613d681aefcb2baffcbb662027d629b8a5b0b7#diff-37854d19817c792316d481f5beb93cc7L73).

**Comment by deavmi** [comment]
@Walkman100 thanks. :)
